<?php
/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostLib\Models;

/**
 * Indicate the action (add or subtract) to be taken.Allowed values increase, decrease
 */
class ActionEnum
{
    /**
     * TODO: Write general description for this element
     */
    const INCREASE = "increase";

    /**
     * TODO: Write general description for this element
     */
    const DECREASE = "decrease";
}
