<?php
/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostLib\Models;

use JsonSerializable;

/**
 *Add Suppression modal
 */
class AddemailordomaintoSuppressionlist implements JsonSerializable
{
    /**
     * Add the domain to be suppressed here. We will not deliver emails to recipients email addresses with
     * this domain.<br>\nComma separate the values to suppress multiple domains..
     * @var string|null $domain public property
     */
    public $domain;

    /**
     * Add an email address to be suppressed here. We will not deliver emails to this email address.
     * <br>\nComma separate the values to suppress multiple email addresses
     * @var string|null $email public property
     */
    public $email;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $domain Initialization value for $this->domain
     * @param string $email  Initialization value for $this->email
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->domain = func_get_arg(0);
            $this->email  = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['domain'] = $this->domain;
        $json['email']  = $this->email;

        return $json;
    }
}
