<?php
/*
 * PepipostAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Attachments implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var string|null $fileContent public property
     */
    public $fileContent;

    /**
     * @todo Write general description for this property
     * @var string|null $fileName public property
     */
    public $fileName;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $fileContent Initialization value for $this->fileContent
     * @param string $fileName    Initialization value for $this->fileName
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->fileContent = func_get_arg(0);
            $this->fileName    = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['fileContent'] = $this->fileContent;
        $json['fileName']    = $this->fileName;

        return $json;
    }
}
