<?php
/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostLib\Models;

use JsonSerializable;

/**
 *Attachments
 */
class Attachments implements JsonSerializable
{
    /**
     * Base64 encoded value of the attached file
     * @var string|null $content public property
     */
    public $content;

    /**
     * filename of attachments
     * @var string|null $name public property
     */
    public $name;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $content Initialization value for $this->content
     * @param string $name    Initialization value for $this->name
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->content = func_get_arg(0);
            $this->name    = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['content'] = $this->content;
        $json['name']    = $this->name;

        return $json;
    }
}
