<?php 
/*
 * PepipostAPIV10Lib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/08/2016
 */

namespace PepipostAPIV10Lib\Models;

use JsonSerializable;

class Attributes implements JsonSerializable {
    /**
     * TODO: Write general description for this property
     * @param array|null $nAME public property
     */
    protected $nAME;

    /**
     * TODO: Write general description for this property
     * @param array|null $rEGID public property
     */
    protected $rEGID;

    /**
     * Constructor to set initial or default values of member properties
	 * @param   array|null        $nAME    Initialization value for the property $this->nAME 
	 * @param   array|null        $rEGID   Initialization value for the property $this->rEGID
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->nAME  = func_get_arg(0);
            $this->rEGID = func_get_arg(1);
        }
    }

    /**
     * Return a property of the response if it exists.
     * Possibilities include: code, raw_body, headers, body (if the response is json-decodable)
     * @return mixed
     */
    public function __get($property)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            $value = $this->$property;
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                return utf8_encode($value);
            }
            else {
                return $value;
            }
        }
    }
    
    /**
     * Set the properties of this object
     * @param string $property the property name
     * @param mixed $value the property value
     */
    public function __set($property, $value)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                $this->$property = utf8_encode($value);
            }
            else {
                $this->$property = $value;
            }
        }

        return $this;
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['NAME']  = $this->nAME;
        $json['REGID'] = $this->rEGID;
        return $json;
    }
}