<?php
/*
 * PepipostAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Attribute implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var string|null $myname public property
     */
    public $myname;

    /**
     * @todo Write general description for this property
     * @var string|null $age public property
     */
    public $age;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $myname Initialization value for $this->myname
     * @param string $age    Initialization value for $this->age
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->myname = func_get_arg(0);
            $this->age    = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['myname'] = $this->myname;
        $json['age']    = $this->age;

        return $json;
    }
}
