<?php
/*
 * PepipostAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostAPILib\Models;

use PepipostAPILib\APIHelper;

/**
 * @todo Write general description for this model
 */
class Attributes
{
    /**
     * @todo Write general description for this property
     * @var string|null $attributes public property
     */
    public $attributes;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $attributes Initialization value for $this->attributes
     */
    public function __construct()
    {
        if (func_num_args() > 0) {
            $this->attributes = func_get_arg(0);
        }
    }

    /**
     * Get attributes in arraylist format
     */
    public function getAttributes()
    {
        if ($this->attributes == null || empty($this->attributes)) {
            return null;
        }
        return APIHelper::deserialize($this->attributes);
    }
}
