<?php
/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostLib\Models;

use JsonSerializable;

/**
 *AMP, HTML should be provided
 */
class Content implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var string|null $type public property
     */
    public $type;

    /**
     * HTML content to be sent in your email
     * @var string|null $value public property
     */
    public $value;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $type  Initialization value for $this->type
     * @param string $value Initialization value for $this->value
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->type  = func_get_arg(0);
            $this->value = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['type']  = $this->type;
        $json['value'] = utf8_encode($this->value);

        return $json;
    }
}
