<?php
/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostLib\Models;

use JsonSerializable;

/**
 *Deletesubaccount modal
 */
class Deletesubacoount implements JsonSerializable
{
    /**
     * The username of the subaccount
     * @var string|null $username public property
     */
    public $username;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $username Initialization value for $this->username
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->username = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['username'] = $this->username;

        return $json;
    }
}
