<?php
/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostLib\Models;

use JsonSerializable;

/**
 *delete domain modal
 */
class Deletedomain implements JsonSerializable
{
    /**
     * Name of the domain
     * @var string|null $domain public property
     */
    public $domain;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $domain Initialization value for $this->domain
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->domain = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['domain'] = $this->domain;

        return $json;
    }
}
