<?php
/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostLib\Models;

use JsonSerializable;

/**
 *Domain Modal
 */
class DomainStruct implements JsonSerializable
{
    /**
     * The domain you wish to include in the 'From' header of your emails.
     * @required
     * @var string $domain public property
     */
    public $domain;

    /**
     * The subdomain which will be used for tracking opens, clicks and unsubscribe
     * @var string|null $envelopeName public property
     */
    public $envelopeName;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $domain       Initialization value for $this->domain
     * @param string $envelopeName Initialization value for $this->envelopeName
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->domain       = func_get_arg(0);
            $this->envelopeName = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['domain']       = $this->domain;
        $json['envelopeName'] = $this->envelopeName;

        return $json;
    }
}
