<?php
/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostLib\Models;

use JsonSerializable;

/**
 *To, CC  and Bcc email Address structure
 */
class EmailStruct implements JsonSerializable
{
    /**
     * Name of recipient
     * @var string|null $name public property
     */
    public $name;

    /**
     * Email of recipient
     * @var string|null $email public property
     */
    public $email;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $name  Initialization value for $this->name
     * @param string $email Initialization value for $this->email
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->name  = func_get_arg(0);
            $this->email = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']  = $this->name;
        $json['email'] = $this->email;

        return $json;
    }
}
