<?php
/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostLib\Models;

/**
 * @todo Write general description for this enumeration
 */
class EventsEnum
{
    /**
     * TODO: Write general description for this element
     */
    const PROCESSED = "processed";

    /**
     * TODO: Write general description for this element
     */
    const SENT = "sent";

    /**
     * TODO: Write general description for this element
     */
    const OPEN = "open";

    /**
     * TODO: Write general description for this element
     */
    const CLICK = "click";

    /**
     * TODO: Write general description for this element
     */
    const UNSUBSCRIBE = "unsubscribe";

    /**
     * TODO: Write general description for this element
     */
    const BOUNCE = "bounce";

    /**
     * TODO: Write general description for this element
     */
    const SOFTBOUNCE = "softbounce";

    /**
     * TODO: Write general description for this element
     */
    const SPAM = "spam";

    /**
     * TODO: Write general description for this element
     */
    const INVALID = "invalid";

    /**
     * TODO: Write general description for this element
     */
    const DROPPED = "dropped";

    /**
     * TODO: Write general description for this element
     */
    const HARDBOUNCE = "hardbounce";
}
