<?php
/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostLib\Models;

use JsonSerializable;

/**
 *Email address representing the sender of the mail
 */
class From implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var string|null $email public property
     */
    public $email;

    /**
     * @todo Write general description for this property
     * @var string|null $name public property
     */
    public $name;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $email Initialization value for $this->email
     * @param string $name  Initialization value for $this->name
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->email = func_get_arg(0);
            $this->name  = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['email'] = $this->email;
        $json['name']  = $this->name;

        return $json;
    }
}
