<?php
/*
 * PepipostAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class From implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var string|null $fromEmail public property
     */
    public $fromEmail;

    /**
     * @todo Write general description for this property
     * @var string|null $fromName public property
     */
    public $fromName;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $fromEmail Initialization value for $this->fromEmail
     * @param string $fromName  Initialization value for $this->fromName
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->fromEmail = func_get_arg(0);
            $this->fromName  = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['fromEmail'] = $this->fromEmail;
        $json['fromName']  = $this->fromName;

        return $json;
    }
}
