<?php
/*
 * PepipostAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostAPILib\Models;

use JsonSerializable;

/**
 *This consits of personlized attachments with recipient,recipient_cc,etc.
 */
class Personalizations implements JsonSerializable
{
    /**
     * Emails to be passed in Apicall
     * @var string|null $recipient public property
     */
    public $recipient;

    /**
     * @todo Write general description for this property
     * @maps x-apiheader_cc
     * @var string|null $xApiheaderCc public property
     */
    public $xApiheaderCc;

    /**
     * @todo Write general description for this property
     * @maps x-apiheader
     * @var string|null $xApiheader public property
     */
    public $xApiheader;

    /**
     * @todo Write general description for this property
     * @var object|null $attributes public property
     */
    public $attributes;

    /**
     * @todo Write general description for this property
     * @var \PepipostAPILib\Models\Attachments[]|null $attachments public property
     */
    public $attachments;

    /**
     * @todo Write general description for this property
     * @maps recipient_cc
     * @var array|null $recipientCc public property
     */
    public $recipientCc;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $recipient    Initialization value for $this->recipient
     * @param string $xApiheaderCc Initialization value for $this->xApiheaderCc
     * @param string $xApiheader   Initialization value for $this->xApiheader
     * @param object $attributes   Initialization value for $this->attributes
     * @param array  $attachments  Initialization value for $this->attachments
     * @param array  $recipientCc  Initialization value for $this->recipientCc
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->recipient    = func_get_arg(0);
            $this->xApiheaderCc = func_get_arg(1);
            $this->xApiheader   = func_get_arg(2);
            $this->attributes   = func_get_arg(3);
            $this->attachments  = func_get_arg(4);
            $this->recipientCc  = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['recipient']      = $this->recipient;
        $json['x-apiheader_cc'] = $this->xApiheaderCc;
        $json['x-apiheader']    = $this->xApiheader;
        $json['attributes']     = $this->attributes;
        $json['attachments']    = $this->attachments;
        $json['recipient_cc']   = $this->recipientCc;

        return $json;
    }
}
