<?php
/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostLib\Models;

use JsonSerializable;

/**
 *Personalizations
 */
class Personalizations implements JsonSerializable
{
    /**
     * Dynamic attributes
     * @var object|null $attributes public property
     */
    public $attributes;

    /**
     * Dynamic headers attributes
     * @var object|null $headers public property
     */
    public $headers;

    /**
     * Attachments to individuals recipient
     * @var \PepipostLib\Models\Attachments[]|null $attachments public property
     */
    public $attachments;

    /**
     * To email-address
     * @required
     * @var \PepipostLib\Models\EmailStruct[] $to public property
     */
    public $to;

    /**
     * CC email-address
     * @var \PepipostLib\Models\EmailStruct[]|null $cc public property
     */
    public $cc;

    /**
     * Bcc email-addresses
     * @var \PepipostLib\Models\EmailStruct[]|null $bcc public property
     */
    public $bcc;

    /**
     * token to which is json string
     * @maps token_to
     * @var string|null $tokenTo public property
     */
    public $tokenTo;

    /**
     * token cc which is json string
     * @maps token_cc
     * @var string|null $tokenCc public property
     */
    public $tokenCc;

    /**
     * token bcc which is json string
     * @maps token_bcc
     * @var string|null $tokenBcc public property
     */
    public $tokenBcc;

    /**
     * Constructor to set initial or default values of member properties
     * @param object $attributes  Initialization value for $this->attributes
     * @param object $headers     Initialization value for $this->headers
     * @param array  $attachments Initialization value for $this->attachments
     * @param array  $to          Initialization value for $this->to
     * @param array  $cc          Initialization value for $this->cc
     * @param array  $bcc         Initialization value for $this->bcc
     * @param string $tokenTo     Initialization value for $this->tokenTo
     * @param string $tokenCc     Initialization value for $this->tokenCc
     * @param string $tokenBcc    Initialization value for $this->tokenBcc
     */
    public function __construct()
    {
        if (9 == func_num_args()) {
            $this->attributes  = func_get_arg(0);
            $this->headers     = func_get_arg(1);
            $this->attachments = func_get_arg(2);
            $this->to          = func_get_arg(3);
            $this->cc          = func_get_arg(4);
            $this->bcc         = func_get_arg(5);
            $this->tokenTo     = func_get_arg(6);
            $this->tokenCc     = func_get_arg(7);
            $this->tokenBcc    = func_get_arg(8);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['attributes']  = $this->attributes;
        $json['headers']     = $this->headers;
        $json['attachments'] = $this->attachments;
        $json['to']          = $this->to;
        $json['cc']          = $this->cc;
        $json['bcc']         = $this->bcc;
        $json['token_to']    = $this->tokenTo;
        $json['token_cc']    = $this->tokenCc;
        $json['token_bcc']   = $this->tokenBcc;

        return $json;
    }
}
