<?php
/*
 * PepipostAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Settings implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var integer|null $footer public property
     */
    public $footer;

    /**
     * @todo Write general description for this property
     * @var integer|null $clicktrack public property
     */
    public $clicktrack;

    /**
     * @todo Write general description for this property
     * @var integer|null $opentrack public property
     */
    public $opentrack;

    /**
     * @todo Write general description for this property
     * @var integer|null $unsubscribe public property
     */
    public $unsubscribe;

    /**
     * @todo Write general description for this property
     * @var string|null $bcc public property
     */
    public $bcc;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $footer      Initialization value for $this->footer
     * @param integer $clicktrack  Initialization value for $this->clicktrack
     * @param integer $opentrack   Initialization value for $this->opentrack
     * @param integer $unsubscribe Initialization value for $this->unsubscribe
     * @param string  $bcc         Initialization value for $this->bcc
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->footer      = func_get_arg(0);
            $this->clicktrack  = func_get_arg(1);
            $this->opentrack   = func_get_arg(2);
            $this->unsubscribe = func_get_arg(3);
            $this->bcc         = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['footer']      = $this->footer;
        $json['clicktrack']  = $this->clicktrack;
        $json['opentrack']   = $this->opentrack;
        $json['unsubscribe'] = $this->unsubscribe;
        $json['bcc']         = $this->bcc;

        return $json;
    }
}
