<?php
/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostLib\Models;

/**
 * @todo Write general description for this enumeration
 */
class StatusEnum
{
    /**
     * TODO: Write general description for this element
     */
    const DOMAIN = "domain";
}
