<?php
/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostLib\Models;

/**
 * The periodic \n\nAllowed values  \"daily\", \"weekly\", \"monhtly\"
 */
class TimeperiodEnum
{
    /**
     * TODO: Write general description for this element
     */
    const DAILY = "daily";

    /**
     * TODO: Write general description for this element
     */
    const WEEKLY = "weekly";

    /**
     * TODO: Write general description for this element
     */
    const MONHTLY = "monhtly";
}
