<?php
/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostLib\Models;

use JsonSerializable;

/**
 *UpdateCreditaccount modal
 */
class UpdateCredisofsubaccount implements JsonSerializable
{
    /**
     * The username of the subaccount
     * @var string|null $username public property
     */
    public $username;

    /**
     * Indicate the action (add or subtract) to be taken.Allowed values increase, decrease
     * @var string|null $action public property
     */
    public $action;

    /**
     * Amount of credits
     * @var integer|null $amount public property
     */
    public $amount;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $username Initialization value for $this->username
     * @param string  $action   Initialization value for $this->action
     * @param integer $amount   Initialization value for $this->amount
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->username = func_get_arg(0);
            $this->action   = func_get_arg(1);
            $this->amount   = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['username'] = $this->username;
        $json['action']   = $this->action;
        $json['amount']   = $this->amount;

        return $json;
    }
}
