<?php
/*
 * PepipostAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostAPILib\Models;

use PepipostAPILib\APIHelper;

/**
 * @todo Write general description for this model
 */
class Xheaders
{
    /**
     * @todo Write general description for this property
     * @var string|null $xheaders public property
     */
    public $xheaders;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $xheaders Initialization value for $this->xheaders
     */
    public function __construct()
    {
        if (func_num_args() > 0) {
            $this->xheaders = func_get_arg(0);
        }
    }

    /**
     * Get attributes in arraylist format
     */
    public function getXheaders()
    {
        if ($this->xheaders == null || empty($this->xheaders)) {
            return null;
        }
        return APIHelper::deserialize($this->xheaders);
    }
}
