<?php
/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostLib;

/**
 * All configuration including auth info and base URI for the API access
 * are configured in this class.
 */
class Configuration
{
    /**
     * The base Uri for API calls
     * @var string
     */
    public static $BASEURI = 'https://api.pepipost.com/v5.1';

    /**
     * Your Pepipost API Key. You will find the api key in the Pepipost application in Integrations.
     * @var string
     */
    public static $apiKey = '';
}
