<?php
/*
 * PepipostAPIV10Lib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/08/2016
 */

namespace PepipostAPIV10Lib;

class Configuration {
    //The base Uri for API calls
    public static $BASEURI = 'https://api.pepipost.com';

}
