<?php
/*
 * PepipostAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PepipostAPILib;

use PepipostAPILib\Controllers;

/**
 * PepipostAPILib client class
 */
class PepipostAPIClient
{
    /**
     * Singleton access to Email controller
     * @return Controllers\EmailController The *Singleton* instance
     */
    public function getEmail()
    {
        return Controllers\EmailController::getInstance();
    }
}
